# Generated by Django 5.1.5 on 2025-01-17 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.PositiveIntegerField(blank=True, null=True)),
                ('defender_card', models.PositiveIntegerField(blank=True, null=True)),
                ('winning_condition', models.CharField(choices=[('HIGH', 'Higher number wins'), ('LOW', 'Lower number wins')], default='HIGH', max_length=10)),
                ('result', models.CharField(blank=True, max_length=10)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_attacked', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_defended', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
