# Generated by Django 5.1.5 on 2025-01-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.PositiveIntegerField(blank=True, null=True)),
                ('defender_card', models.PositiveIntegerField(blank=True, null=True)),
                ('winning_condition', models.CharField(choices=[('HIGH', 'Higher number wins'), ('LOW', 'Lower number wins')], default='HIGH', max_length=10)),
                ('result', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
